### ISSUE TITLE
Monotonicity is calculated to the second instead of millisecond

### ISSUE THREAD

**Issue by ralphschindler** [robinvdvleuten/php-ulid#18]
https://github.com/ulid/spec#monotonicity

By casting to `(int)` at https://github.com/robinvdvleuten/php-ulid/blob/master/src/Ulid.php#L69 this is removing the float portion of the return value of `microtime(true)` thus checking if the current call happened within the same second (instead of millisecond) of the last request.

This should be changed such that it uses the value: `microtime(true) * 1000` for milliseconds.

**Comment by sarlisj** [comment]
please help me with zendframework cannot install in UBUNTU 16.04

curl -s http://getcomposer.org/installer | php
All settings correct for using Composer
Downloading...

Composer (version 1.8.6) successfully installed to: /var/www/composer.phar
Use it: php composer.phar

www-data@myserver:~$ php composer.phar install
You are running Composer with SSL/TLS protection disabled.
Loading composer repositories with package information


  [Composer\Downloader\TransportException]
  Your configuration does not allow connections to http://packages.zendframew
  ork.com/packages.json. See https://getcomposer.org/doc/06-config.md#secure-
  http for details.

**Comment by robinvdvleuten** [comment]
Good catch! Thanks, I've fixed it immediately.
