### ISSUE TITLE
decodeTime() return incorrect timestamp

### ISSUE THREAD

**Issue by DenisGavrilov** [robinvdvleuten/php-ulid#23]
Good day.
Method decodeTime() return incorrect timestamp.
In method generate(): $now = (int) (microtime(true) * 1000);.
Maybe decodeTime() must return $carry/1000 ?

**Comment by robinvdvleuten** [comment]
Could you make a PR to fix this?

**Comment by robinvdvleuten** [comment]
As it seems that the method is tested correctly https://github.com/robinvdvleuten/php-ulid/blob/master/tests/UlidTest.php#L117

**Comment by DenisGavrilov** [comment]
I think this test maked before this commit https://github.com/robinvdvleuten/php-ulid/commit/28dfc9285affa01385c175bb7fb5289791980edb
PR will try. I'm a beginner.

**Comment by robinvdvleuten** [comment]
See https://github.com/robinvdvleuten/php-ulid/pull/24#issuecomment-644025579 on why this is not an issue.
