### ISSUE TITLE
Generated ULID isn't unique

### ISSUE THREAD

**Issue by icobg** [robinvdvleuten/php-ulid#31]
Hello,
I was try the script, but it's seems ulid's last 80 bits isn't unique. Here is example:
$php  rr.php
01F46VF3ZZR6FYNWDYQXFA9NQT
01f46vf3zzr6fynwdyqxfa9nqv

and here is the script:

    include 'Ulid/Ulid.php';
    use Ulid\Ulid;

    $ulid = Ulid::generate();
    echo (string) $ulid, "\n"; // 01F46VF3ZZR6FYNWDYQXFA9NQT

    // Or if you prefer a lowercased output
    $ulid = Ulid::generate(true);
    echo (string) $ulid, "\n"; // 01f46vf3zzr6fynwdyqxfa9nqv

Only the last char is different, but in specification last  80 bits need to be unique for example in Postgres ulid:

# select generate_ulid() from generate_series(1, 10);
       generate_ulid        
----------------------------
 01F46WA08EPZTRXY4108T4XAMA
 01F46WA08ET4RGV447EKD337ES
 01F46WA08EHWXAGBSWQMWHZVHK
 01F46WA08EZTD358CC7YGKPRKX
 01F46WA08EWRBMMJHCA335794Q
 01F46WA08EG7H98DZY789T48VH
 01F46WA08EY4X6MQW5986SAP82
 01F46WA08EXY9BM9YY284C7GM2
 01F46WA08E2W1CTYQ9CX1JW02N
 01F46WA08EW8ESAW6QBD65ZK4A
(10 rows)

**Comment by batyrmastyr** [comment]
@icobg I see `When generating a ULID within the same millisecond, we can provide some guarantees regarding sort order. Namely, if the same millisecond is detected, the random component is incremented by 1 bit in the least significant bit position (with carrying).`, so the implementation seem to be correct.

**Comment by icobg** [comment]
Okay, but last 80 bits is not unique, they are the same but they must be unique. Check the postgresql example above made in the same second. As you can see, after time 01F46WA08E other part is completely unique, your is the same R6FYNWDYQXFA9NQ = r6fynwdyqxfa9nq. If you think everything is okay, close the issue.

**Comment by robinvdvleuten** [comment]
As @batyrmastyr already mentions, when creating within same millisecond the last 1 bit is shifted.

**Comment by AlexStiyer** [comment]
@robinvdvleuten there is a huge problem with this approach when generating ULIDS for the same timestamp. If the application restarts it always starts with the same ULID for the supplied timestamp. There needs to be some way of supplying a seed to the random bits so that it can be unique cross runs.

**Comment by batyrmastyr** [comment]
@AlexStiyer are you sure? There is a test `\Ulid\Tests\UlidTest::testAddsRandomnessWhenGeneratedMultipleTimesByFromTimestamp` that ensures uniqueness for same timestamp.
I made a small test for myself
```php
<?php
use Ulid\Ulid;
require __DIR__.'/vendor/autoload.php';
$milliseconds = 1593048767015;
$a = Ulid::fromTimestamp($milliseconds);
var_dump((string)$a);
```
Output was unique:
```bash
php -f test.php                                                                                                                       22:33:48
string(26) "01EBMHP6H7MKH7BJFXSE03CXCA"
~/D/n/php-ulid (master|✚3…) $ php -f test.php                                                                                                                      22:35:02
string(26) "01EBMHP6H704FGP2KGXMSKTYWJ"
~/D/n/php-ulid (master|✚3…) $ php -f test.php                                                                                                                      22:35:03
string(26) "01EBMHP6H7NBDMBFRCPQZ8TMS5"
~/D/n/php-ulid (master|✚3…) $ php -f test.php                                                                                                                      22:35:05
string(26) "01EBMHP6H74JX7H1XT9XAK97QG"
```

**Comment by AlexStiyer** [comment]
@batyrmastyr Thank you for running a test! Unfortunately, I have a couple million rows in my database saying otherwise.

Though I should add that our timestamps were only accurate to the second. Is there an issue when there isn't millisecond accuracy in the timestamp?

**Comment by batyrmastyr** [comment]
Code stores only previous timestamp to determine if it should randomize, so if you used ::fromTimestamp with ordered by timestamp data, then yes, within a second there will be only increments.
I guess expected way of use - ::generate.
