### ISSUE TITLE
Uppercase by default?

### ISSUE THREAD

**Issue by mv-i22** [robinvdvleuten/php-ulid#4]
The ulid spec does not state it explicitly, but aren't ulids supposed to be uppercase? Lowercase won't change anything when sorting and it might take less memory and database in some circumstances, but shouldn't the technique be the same over all languages?

Otherwise: Thanks for the library, good job! 👍

**Comment by robinvdvleuten** [comment]
@mv-i22 that's the reason why I stated `A PHP port of alizain/ulid with some minor improvements.` within the README. I use the ulid in my URLs and JSON responses and I find it cleaner to have them lowercase there. To prevent myself from coding a lot of "uppercase/lowercase" serialization, I made them already lowercase here :)

**Comment by mv-i22** [comment]
I find that debatable because it makes ULID inconsistent between languages. That _could_ lead to problems in cross language environments. But that's just my opinion. For my current project, I'll have to uppercase the ULIDs before using them in order to prevent potential bugs coming from regexes in other languages or stuff like this.

In order to make ULID consistent, this should be added to the specs, I guess...

**Comment by robinvdvleuten** [comment]
Maybe it would be a nice addition to make the casing optional through a constructor argument.

**Comment by mv-i22** [comment]
Maybe. but again, this is a thought that will have to be made when using the library (or using ULID). I'd prefer the standard spec to have this straight. But maybe I'm too imposing there... I'll try to hear what alizain thinks about this.

**Comment by mv-i22** [comment]
Quick reference: https://github.com/ulid/spec/issues/3

**Comment by nelsonjchen** [comment]
This response on that issue should be considered: https://github.com/ulid/spec/issues/3#issuecomment-406077611
